In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import datetime as dt

from pathlib import Path
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

project_dir = Path.cwd()
data_dir = project_dir / 'Raw Data'

In [4]:
# load single-store sales data
sales_long = pd.read_csv(
    data_dir / 'sales_long.csv',
    parse_dates=['date'],
    low_memory=False
)

In [3]:
# recall the level of this dataset
# i.e. a single store with many items over many dates
sales_long.groupby(['store_id','date','cat_id'])[['item_id']].nunique()

                               item_id
store_id date       cat_id
CA_1     2011-01-29 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-01-30 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-01-31 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-01 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-02 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-03 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-04 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-05 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-06 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-07 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-08 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-09 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-10 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-11 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-12 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-13 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-14 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-15 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-16 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-17 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-18 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-19 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-20 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-21 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-22 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-23 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-24 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-25 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-26 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-27 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-02-28 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-01 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-02 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-03 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-04 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-05 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-06 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-07 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-08 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-09 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-10 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-11 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-12 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-13 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-14 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-15 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-16 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-17 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-18 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-19 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-20 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-21 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-22 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-23 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-24 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-25 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-26 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-27 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-28 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-29 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-30 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-03-31 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-01 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-02 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-03 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-04 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-05 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-06 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-07 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-08 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-09 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-10 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-11 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-12 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-13 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-14 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-15 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-16 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-17 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-18 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-19 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-20 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-21 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-22 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-23 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-24 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-25 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-26 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-27 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-28 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-29 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-04-30 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-01 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-02 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-03 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-04 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-05 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-06 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-07 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-08 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-09 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-10 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-11 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-12 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-13 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-14 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-15 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-16 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-17 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-18 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-19 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-20 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-21 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-22 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-23 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-24 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-25 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-26 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-27 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-28 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-29 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-30 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-05-31 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-01 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-02 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-03 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-04 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-05 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-06 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-07 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-08 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-09 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-10 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-11 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-12 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-13 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-14 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-15 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-16 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-17 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-18 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-19 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-20 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-21 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-22 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-23 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-24 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-25 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-26 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-27 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-28 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-29 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-06-30 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-07-01 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-07-02 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-07-03 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-07-04 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-07-05 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-07-06 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-07-07 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-07-08 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-07-09 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-07-10 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-07-11 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-07-12 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-07-13 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-07-14 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-07-15 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-07-16 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-07-17 FOODS         1437
                    HOBBIES        565
                    HOUSEHOLD     1047
         2011-07-18 FOODS         1437

# Create inventory summary

In [5]:
# summarize historical demand by product
inventory_summary = (
    sales_long
    .groupby('item_id', observed=True)
    .agg(
        average_daily_demand=('units_sold', 'mean'),
        daily_demand_std=('units_sold', 'std'),
        total_units_sold=('units_sold', 'sum'),
        zero_demand_days=('units_sold', lambda x: (x == 0).sum()),
        days_observed=('units_sold', 'count')
    )
    .reset_index()
)

# calculate the percentage of days with zero demand
inventory_summary['zero_demand_pct'] = (
    inventory_summary['zero_demand_days']
    / inventory_summary['days_observed']
    * 100
)

# rank products by average daily demand
inventory_summary = inventory_summary.sort_values(
    'average_daily_demand',
    ascending=False
).reset_index(drop=True)

# inspect the results
print(f'Products: {inventory_summary["item_id"].nunique():,}')
print(f'Date range: {sales_long["date"].min().date()} to {sales_long["date"].max().date()}')

display(inventory_summary.round(2).head(20))

Products: 3,049
Date range: 2011-01-29 to 2016-04-24
Days observed per product: 1913–1913

,item_id,average_daily_demand,daily_demand_std,total_units_sold,zero_demand_days,days_observed,zero_demand_pct
0,FOODS_3_090,66.49,57.86,127203,469,1913,24.52
1,FOODS_3_586,45.84,16.40,87691,7,1913,0.37
2,FOODS_3_252,39.19,18.72,74971,6,1913,0.31
3,FOODS_3_120,32.36,33.54,61899,667,1913,34.87
4,FOODS_3_714,28.27,14.50,54080,7,1913,0.37
5,FOODS_3_587,27.03,21.45,51717,455,1913,23.78
6,FOODS_3_808,24.10,24.41,46094,385,1913,20.13
7,FOODS_2_197,21.27,12.74,40698,159,1913,8.31
8,FOODS_3_080,20.46,7.76,39145,6,1913,0.31
9,FOODS_3_555,19.80,7.83,37871,6,1913,0.31
10,FOODS_3_541,19.04,19.17,36420,389,1913,20.33
11,FOODS_3_741,18.48,13.71,35351,124,1913,6.48
12,FOODS_2_019,18.47,10.98,35324,162,1913,8.47
13,FOODS_3_635,18.13,19.17,34681,450,1913,23.52
14,FOODS_3_099,17.35,7.92,33194,91,1913,4.76
15,FOODS_3_681,17.22,16.56,32941,179,1913,9.36
16,FOODS_3_318,17.05,22.11,32622,579,1913,30.27
17,FOODS_3_202,16.40,10.21,31379,211,1913,11.03
18,FOODS_3_282,15.30,19.02,29272,951,1913,49.71
19,FOODS_3_694,15.19,6.74,29060,8,1913,0.42